using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Text;
using System.Linq;

namespace Nox.Generator.Generators
{
    internal abstract class BaseGenerator
    {
        protected GeneratorExecutionContext Context { get; }

        internal BaseGenerator(GeneratorExecutionContext context)
        {
            Context = context;
        }

        protected void GenerateFile(StringBuilder sb, string className)
        {
            var hintName = $"{className}.g.cs";
            var source = SourceText.From(sb.ToString(), Encoding.UTF8);

            Context.AddSource(hintName, source);
        }

        protected static void AddConstructor(StringBuilder sb, string className)
        {
            sb.AppendLine($@"   public {className}(");
            sb.AppendLine($@"      NoxDbContext dbContext");
            sb.AppendLine($@"      )");
            sb.AppendLine($@"   {{");
            sb.AppendLine($@"      DbContext = dbContext;");
            sb.AppendLine($@"   }}");
            sb.AppendLine($@"");
        }

        protected static string GetParametersString(object entity)
        {
            return string.Join(", ", ((List<object>)entity).Cast<Dictionary<object, object>>()
                .Select(parameter => $"{parameter["type"]} {parameter["name"]}"));
        }

        protected static void AddDbContextProperty(StringBuilder sb)
        {
            sb.AppendLine($@"   protected NoxDbContext DbContext {{ get; init; }}");
            sb.AppendLine($@"");
        }

        protected static void AddAttributes(Dictionary<object, object> entity, StringBuilder sb)
        {
            var attributes = (List<object>)entity["attributes"];

            foreach (var attr in attributes.Cast<Dictionary<object, object>>())
            {
                sb.AppendLine($@"   public {ClassDataType((string)attr["type"])} {attr["name"]} {{get; set;}}");
                sb.AppendLine($@"");
            }
        }

        protected static void AddNoxMessangerProperty(StringBuilder sb)
        {
            sb.AppendLine($@"   protected INoxMessenger Messenger {{ get; init; }}");
            sb.AppendLine($@"");
        }

        protected static void AddDomainEvent(StringBuilder sb, string eventName)
        {
            sb.AppendLine($@"   public {eventName}DomainEvent {eventName} {{get; init;}}");
            sb.AppendLine($@"");
        }

        protected static void AddBaseTypeDefinition(
            StringBuilder sb,
            string className,
            string parent,
            string noxNamespace,
            bool isAbstract = false,
            params string[] namespaces)
        {
            sb.AppendLine($@"// autogenerated");
            foreach (var val in namespaces)
            {
                sb.AppendLine($@"using {val};");
            }

            sb.AppendLine($@"");
            sb.AppendLine($@"namespace {noxNamespace};");
            sb.AppendLine($@"");
            sb.AppendLine($@"public {(isAbstract ? "abstract " : string.Empty)}class {className} : {parent}");
            sb.AppendLine($@"{{");
        }

        protected static bool GetBooleanValueOrDefault(Dictionary<object, object> entity, string key)
        {
            entity.TryGetValue(key, out object val);

            var valString = (string)val;

            // cover yes/no and true/false
            return valString != null && (valString.Equals("yes") || !valString.Equals("no") && bool.Parse(valString));
        }

        protected static string ClassDataType(string type)
        {
            var propType = type?.ToLower() ?? "string";

            return propType switch
            {
                "string" => "string",
                "varchar" => "string",
                "nvarchar" => "string",
                "char" => "string",
                "guid" => "Guid",
                "url" => "string",
                "email" => "string",
                "date" => "DateTime",
                "time" => "DateTime",
                "timespan" => "TimeSpan",
                "datetime" => "DateTimeOffset",
                "bool" => "bool",
                "boolean" => "bool",
                "object" => "object",
                "int" => "int",
                "uint" => "uint",
                "tinyint" => "int",
                "bigint" => "long",
                "money" => "decimal",
                "smallmoney" => "decimal",
                "decimal" => "decimal",
                "real" => "single",
                "float" => "single",
                "bigreal" => "double",
                "bigfloat" => "double",
                _ => "string"
            };
        }
    }
}
