//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nox.Core {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nox.Core.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ApiNameEmpty {
            get {
                return ResourceManager.GetString("ApiNameEmpty", resourceCulture);
            }
        }
        
        internal static string ApiRoutesEmpty {
            get {
                return ResourceManager.GetString("ApiRoutesEmpty", resourceCulture);
            }
        }
        
        internal static string ApiRouteNameEmpty {
            get {
                return ResourceManager.GetString("ApiRouteNameEmpty", resourceCulture);
            }
        }
        
        internal static string ApiRouteVerbEmpty {
            get {
                return ResourceManager.GetString("ApiRouteVerbEmpty", resourceCulture);
            }
        }
        
        internal static string ApiRouteTargetUrlEmpty {
            get {
                return ResourceManager.GetString("ApiRouteTargetUrlEmpty", resourceCulture);
            }
        }
        
        internal static string ApiRouteParameterNameEmpty {
            get {
                return ResourceManager.GetString("ApiRouteParameterNameEmpty", resourceCulture);
            }
        }
        
        internal static string ApiRouteParameterTypeEmpty {
            get {
                return ResourceManager.GetString("ApiRouteParameterTypeEmpty", resourceCulture);
            }
        }
        
        internal static string ApiRouteResponseTypeEmpty {
            get {
                return ResourceManager.GetString("ApiRouteResponseTypeEmpty", resourceCulture);
            }
        }
        
        internal static string DbNameEmpty {
            get {
                return ResourceManager.GetString("DbNameEmpty", resourceCulture);
            }
        }
        
        internal static string DbProviderEmpty {
            get {
                return ResourceManager.GetString("DbProviderEmpty", resourceCulture);
            }
        }
        
        internal static string EntityAttributeNameEmpty {
            get {
                return ResourceManager.GetString("EntityAttributeNameEmpty", resourceCulture);
            }
        }
        
        internal static string EntityAttributeTypeEmpty {
            get {
                return ResourceManager.GetString("EntityAttributeTypeEmpty", resourceCulture);
            }
        }
        
        internal static string EntityNameEmpty {
            get {
                return ResourceManager.GetString("EntityNameEmpty", resourceCulture);
            }
        }
        
        internal static string EntityAttributesEmpty {
            get {
                return ResourceManager.GetString("EntityAttributesEmpty", resourceCulture);
            }
        }
        
        internal static string LoaderNameEmpty {
            get {
                return ResourceManager.GetString("LoaderNameEmpty", resourceCulture);
            }
        }
        
        internal static string LoadStrategyTypeInvalid {
            get {
                return ResourceManager.GetString("LoadStrategyTypeInvalid", resourceCulture);
            }
        }
        
        internal static string MessagingProviderNameEmpty {
            get {
                return ResourceManager.GetString("MessagingProviderNameEmpty", resourceCulture);
            }
        }
        
        internal static string MessagingProviderProviderEmpty {
            get {
                return ResourceManager.GetString("MessagingProviderProviderEmpty", resourceCulture);
            }
        }
        
        internal static string LoaderLoadStrategyEmpty {
            get {
                return ResourceManager.GetString("LoaderLoadStrategyEmpty", resourceCulture);
            }
        }
        
        internal static string LoaderTargetEmpty {
            get {
                return ResourceManager.GetString("LoaderTargetEmpty", resourceCulture);
            }
        }
        
        internal static string LoaderTargetEntityEmpty {
            get {
                return ResourceManager.GetString("LoaderTargetEntityEmpty", resourceCulture);
            }
        }
        
        internal static string LoaderMessageTargetProviderEmpty {
            get {
                return ResourceManager.GetString("LoaderMessageTargetProviderEmpty", resourceCulture);
            }
        }
        
        internal static string LoaderDataSourceEmpty {
            get {
                return ResourceManager.GetString("LoaderDataSourceEmpty", resourceCulture);
            }
        }
        
        internal static string LoaderQueryEmpty {
            get {
                return ResourceManager.GetString("LoaderQueryEmpty", resourceCulture);
            }
        }
        
        internal static string ConfigNameEmpty {
            get {
                return ResourceManager.GetString("ConfigNameEmpty", resourceCulture);
            }
        }
        
        internal static string ConfigDbEmpty {
            get {
                return ResourceManager.GetString("ConfigDbEmpty", resourceCulture);
            }
        }
        
        internal static string ConfigEntitiesEmpty {
            get {
                return ResourceManager.GetString("ConfigEntitiesEmpty", resourceCulture);
            }
        }
        
        internal static string LoaderScheduleStartEmpty {
            get {
                return ResourceManager.GetString("LoaderScheduleStartEmpty", resourceCulture);
            }
        }
        
        internal static string LoadStrategyTypeEmpty {
            get {
                return ResourceManager.GetString("LoadStrategyTypeEmpty", resourceCulture);
            }
        }
        
        internal static string LoaderTargetEntityMissing {
            get {
                return ResourceManager.GetString("LoaderTargetEntityMissing", resourceCulture);
            }
        }
        
        internal static string LoaderDataSourceMissing {
            get {
                return ResourceManager.GetString("LoaderDataSourceMissing", resourceCulture);
            }
        }
        
        internal static string LoaderMessageTargetMissing {
            get {
                return ResourceManager.GetString("LoaderMessageTargetMissing", resourceCulture);
            }
        }
    }
}
