//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nox.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nox.Core.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The api&apos;s name must be specified in {0}.
        /// </summary>
        internal static string ApiNameEmpty {
            get {
                return ResourceManager.GetString("ApiNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The api route name must be specified in {0}.
        /// </summary>
        internal static string ApiRouteNameEmpty {
            get {
                return ResourceManager.GetString("ApiRouteNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api route parameter must have a name specified in {0}.
        /// </summary>
        internal static string ApiRouteParameterNameEmpty {
            get {
                return ResourceManager.GetString("ApiRouteParameterNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api route parameter &apos;{0}&apos; must have a type specified in {1}.
        /// </summary>
        internal static string ApiRouteParameterTypeEmpty {
            get {
                return ResourceManager.GetString("ApiRouteParameterTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api route response must have a type specified in {0}.
        /// </summary>
        internal static string ApiRouteResponseTypeEmpty {
            get {
                return ResourceManager.GetString("ApiRouteResponseTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The api must have at least one route defined in {0}.
        /// </summary>
        internal static string ApiRoutesEmpty {
            get {
                return ResourceManager.GetString("ApiRoutesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The api route target url must be specified in {0}.
        /// </summary>
        internal static string ApiRouteTargetUrlEmpty {
            get {
                return ResourceManager.GetString("ApiRouteTargetUrlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The api route http verb must be specified in {0}.
        /// </summary>
        internal static string ApiRouteVerbEmpty {
            get {
                return ResourceManager.GetString("ApiRouteVerbEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Database definition must be specified in {0}.
        /// </summary>
        internal static string ConfigDbEmpty {
            get {
                return ResourceManager.GetString("ConfigDbEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service definition &apos;{0}&apos; must have at least one entity in {1}.
        /// </summary>
        internal static string ConfigEntitiesEmpty {
            get {
                return ResourceManager.GetString("ConfigEntitiesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Name must be specified in {0}.
        /// </summary>
        internal static string ConfigNameEmpty {
            get {
                return ResourceManager.GetString("ConfigNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database/datasource name must be specified in {0}.
        /// </summary>
        internal static string DbNameEmpty {
            get {
                return ResourceManager.GetString("DbNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database/datasource &apos;{0}&apos; provider must be specified in {1}.
        /// </summary>
        internal static string DbProviderEmpty {
            get {
                return ResourceManager.GetString("DbProviderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source provider must be one of {0} in {1}.
        /// </summary>
        internal static string DbProviderInvalid {
            get {
                return ResourceManager.GetString("DbProviderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute name must be specified in {0}.
        /// </summary>
        internal static string EntityAttributeNameEmpty {
            get {
                return ResourceManager.GetString("EntityAttributeNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity &apos;{0}&apos; must have at least one property defined in {1}.
        /// </summary>
        internal static string EntityAttributesEmpty {
            get {
                return ResourceManager.GetString("EntityAttributesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; has no type defined in {1}.
        /// </summary>
        internal static string EntityAttributeTypeEmpty {
            get {
                return ResourceManager.GetString("EntityAttributeTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command name must be specified in {0}.
        /// </summary>
        internal static string EntityCommandNameEmpty {
            get {
                return ResourceManager.GetString("EntityCommandNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event name must be specified in {0}.
        /// </summary>
        internal static string EntityDomainEventNameEmpty {
            get {
                return ResourceManager.GetString("EntityDomainEventNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event type must be specified in {0} for event {1}.
        /// </summary>
        internal static string EntityDomainEventTypeEmpty {
            get {
                return ResourceManager.GetString("EntityDomainEventTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key name must be specified in {0}.
        /// </summary>
        internal static string EntityKeyNameEmpty {
            get {
                return ResourceManager.GetString("EntityKeyNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; has no type defined in {1}.
        /// </summary>
        internal static string EntityKeyTypeEmpty {
            get {
                return ResourceManager.GetString("EntityKeyTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity&apos;s name must be specified in {0}.
        /// </summary>
        internal static string EntityNameEmpty {
            get {
                return ResourceManager.GetString("EntityNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query name must be specified in {0}.
        /// </summary>
        internal static string EntityQueryNameEmpty {
            get {
                return ResourceManager.GetString("EntityQueryNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query parameter name must be specified in {0}.
        /// </summary>
        internal static string EntityQueryParameterNameEmpty {
            get {
                return ResourceManager.GetString("EntityQueryParameterNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query parameter &apos;{0}&apos; has no type defined in {1}.
        /// </summary>
        internal static string EntityQueryParameterTypeEmpty {
            get {
                return ResourceManager.GetString("EntityQueryParameterTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query {0} ResponseDto must be specified in {1}.
        /// </summary>
        internal static string EntityQueryResponseEmpty {
            get {
                return ResourceManager.GetString("EntityQueryResponseEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Loader source is missing a DataSource value in {0}.
        /// </summary>
        internal static string LoaderDataSourceEmpty {
            get {
                return ResourceManager.GetString("LoaderDataSourceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Loader data source {0} in {1} does not exist in the service definition yaml.
        /// </summary>
        internal static string LoaderDataSourceMissing {
            get {
                return ResourceManager.GetString("LoaderDataSourceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Load Strategy must be supplied for Loader &apos;{0}&apos; in {1}.
        /// </summary>
        internal static string LoaderLoadStrategyEmpty {
            get {
                return ResourceManager.GetString("LoaderLoadStrategyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Loader messaging target {0} in {1} does not exist in the service definition yaml.
        /// </summary>
        internal static string LoaderMessageTargetMissing {
            get {
                return ResourceManager.GetString("LoaderMessageTargetMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The messaging provider must be specified in {0}.
        /// </summary>
        internal static string LoaderMessageTargetProviderEmpty {
            get {
                return ResourceManager.GetString("LoaderMessageTargetProviderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loader name must be specified in {0}.
        /// </summary>
        internal static string LoaderNameEmpty {
            get {
                return ResourceManager.GetString("LoaderNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Loader source is missing a Query statement in {0}.
        /// </summary>
        internal static string LoaderQueryEmpty {
            get {
                return ResourceManager.GetString("LoaderQueryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader Schedule must have a Start specified in {0}.
        /// </summary>
        internal static string LoaderScheduleStartEmpty {
            get {
                return ResourceManager.GetString("LoaderScheduleStartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target for loader &apos;{0}&apos; must be specified in {1}.
        /// </summary>
        internal static string LoaderTargetEmpty {
            get {
                return ResourceManager.GetString("LoaderTargetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loader target entity must be specified in {0}.
        /// </summary>
        internal static string LoaderTargetEntityEmpty {
            get {
                return ResourceManager.GetString("LoaderTargetEntityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loader targets a non existing entity {0} in {1}.
        /// </summary>
        internal static string LoaderTargetEntityMissing {
            get {
                return ResourceManager.GetString("LoaderTargetEntityMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader load strategy must have a type specified in {0}.
        /// </summary>
        internal static string LoadStrategyTypeEmpty {
            get {
                return ResourceManager.GetString("LoadStrategyTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load strategy Type must be one of {0} in {1}.
        /// </summary>
        internal static string LoadStrategyTypeInvalid {
            get {
                return ResourceManager.GetString("LoadStrategyTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The messaging provider name must be specified in {0}.
        /// </summary>
        internal static string MessagingProviderNameEmpty {
            get {
                return ResourceManager.GetString("MessagingProviderNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider for messaging provider &apos;{0}&apos; must be specified in {1}.
        /// </summary>
        internal static string MessagingProviderProviderEmpty {
            get {
                return ResourceManager.GetString("MessagingProviderProviderEmpty", resourceCulture);
            }
        }
    }
}
